---
# ansible-playbook -b ansible.yaml --ask-become-pass
# TEST example of an installer using ansible
- name: Docker Install
  hosts: localhost

  tasks:
  - name: Install all packages
    ansible.builtin.package:
      name:
        - ca-certificates
        - curl
        - gnupg

  - name: cleanup old install
    ansible.builtin.package:
      name:
        - docker-engine
        - docker
        - docker.io
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
      state: absent

  - name: add keyring
    ansible.builtin.shell: |
      sudo install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      sudo chmod a+r /etc/apt/keyrings/docker.gpg
      # Add the repository to Apt sources:
      echo \
       "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
       $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
       sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Install docker
    ansible.builtin.package:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  - name: create docker group
    ansible.builtin.shell: |
      sudo groupadd -f docker
      sudo usermod -aG docker $USER
      newgrp docker
      sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
      sudo chmod g+rwx "$HOME/.docker" -R

  - name: enable service
    ansible.builtin.shell: |
      sudo systemctl enable docker.service
      sudo systemctl enable containerd.service
