#!/bin/bash
#	get source code
git clone https://github.com/adobe-fonts/source-code-pro.git
#	Get necessary pip libraries
pip3 install afdko fonttools fontmake
#	Get to the master branch
cd source-code-pro
git checkout master
# 	Build regular style OTF font
# cd Roman/Instances/Regular/
# makeotf -r -gs -omitMacNames
#	Build regular style ttf font
# otf2ttf SourceCodePro-Regular.otf
# ttfcomponentizer SourceCodePro-Regular.ttf
#	Build fonts, variable and non-variable
# cd ../../../
./build.sh
./buildVFs.sh
