---
# ansible-playbook -b fedora.yaml --ask-become-pass
- hosts: localhost
  # var files. File with the os family name will overwrite values in defaults
  vars_files:
  - "defaults.yaml"
  - "{{ ansible_facts['os_family'] }}.yaml"
  tasks:
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Install all packages
    ansible.builtin.package:
      name:
        - "{{ alacritty }}"
        - "{{ binutils }}"
        - "{{ binwalk }}"
          # - "{{ build_essential }}"
        - "{{ ca_certificates }}"
        - "{{ cargo }}"
        - "{{ cfssl }}"
        - "{{ cmake }}"
        - "{{ curl }}"
        - "{{ containerd }}"
        - "{{ crontab }}"
        - "{{ diffutils }}"
        - "{{ direnv }}"
        - "{{ distrobox }}"
        # - "{{ ffmpeg }}"
        - "{{ flatpak }}"
        - "{{ fontconfig }}"
        - "{{ freetype }}"
        # - "{{ gnome_flatpak }}"
        - "{{ golang }}"
        - "{{ gcc }}"
        - "{{ gdb }}"
        - "{{ gplusplus }}"
        - "{{ gettext }}"
        - "{{ git }}"
        - "{{ gitlfs }}"
        - "{{ gnupg }}"
        - "{{ gzip }}"
        - "{{ jq }}"
        - "{{ jdk }}"
        - "{{ imagemagick }}"
        # - "{{ kubectx }}"
        - "{{ launchpad }}"
        # - "{{ libbz2_dev }}"
        # - "{{ libffi_dev }}"
        # - "{{ liblzma_dev }}"
        - "{{ libncursesdev }}"
        # - "{{ libpcsclite_dev }}"
        - "{{ libpq }}"
        - "{{ libreadline }}"
        - "{{ sqlite }}"
        - "{{ libssl_dev }}"
        - "{{ libtool }}"
        - "{{ libxcb }}"
        - "{{ libxkbcommon }}"
        # - "{{ libtool_bin }}"
        # - "{{ libxml2_dev }}"
        # - "{{ libxmlsec1_dev }}"
        - "{{ llvm }}"
        - "{{ lsb_release }}"
        - "{{ make }}"
        - "{{ miniupnpc }}"
        # - "{{ neovim }}"
        - "{{ netcat }}"
        - "{{ ncurses_base }}"
        - "{{ net_tools }}"
        - "{{ neovim }}"
        - "{{ nmap }}"
        # - "{{ nodejs }}"
        - "{{ openssl }}"
        # - "{{ podman }}"
        - "{{ protobuf }}"
        # - "{{ protobuf_compiler }}"
        - "{{ proxychains }}"
        - "{{ pip }}"
        - "{{ pipx }}"
        - "{{ pipenv }}"
        # - "{{ printer_driver }}"
        - "{{ python3 }}"
        - "{{ python_is_python3 }}"
        - "{{ pyvenv }}"
        - "{{ redis }}"
        # - "{{ rust }}"
        - "{{ tcpdump }}"
        - "{{ telnet }}"
        - "{{ texlive }}"
        - "{{ tkinter }}"
        - "{{ tmux }}"
        - "{{ tor }}"
        - "{{ unar }}"
        - "{{ unzip }}"
        - "{{ vim }}"
        - "{{ wget }}"
        - "{{ whois }}"
        - "{{ wmctrl }}"
        - "{{ xrandr }}"
        - "{{ xsel }}"
        # - "{{ xz_utils }}"
        # - "{{ yq }}"
        - "{{ yubikey }}"
        # - "{{ zlib1g_dev }}"
        - "{{ zsh }}"
      state: latest
  - name: Run master file of command line installers
    ansible.builtin.import_tasks:
      file: master.yaml

