---
# ansible-playbook -b packages.yaml --ask-become-pass
- hosts: localhost
  # var files. File with the os family name will overwrite values in defaults
  vars_files:
  - "defaults.yaml"
  - "{{ ansible_facts['os_family'] }}.yaml"
  tasks:
  - name: Install all packages
    ansible.builtin.package:
      name:
        - "{{ binutils }}"
        - "{{ binwalk }}"
        - "{{ build_essential }}"
        - "{{ ca_certificates }}"
        - "{{ cmake }}"
        - "{{ curl }}"
        - "{{ diffutils }}"
        - "{{ distrobox }}"
        - "{{ gcc }}"
        - "{{ gdb }}"
        - "{{ gettext }}"
        - "{{ git }}"
        - "{{ gnupg }}"
        - "{{ gzip }}"
        - "{{ jq }}"
        - "{{ libbz2_dev }}"
        - "{{ libffi_dev }}"
        - "{{ liblzma_dev }}"
        - "{{ libncursesw5_dev }}"
        - "{{ libpcsclite_dev }}"
        - "{{ libreadline_dev }}"
        - "{{ libsqlite3_dev }}"
        - "{{ libssl_dev }}"
        - "{{ libtool }}"
        - "{{ libtool_bin }}"
        - "{{ libxml2_dev }}"
        - "{{ libxmlsec1_dev }}"
        - "{{ llvm }}"
        - "{{ lsb_release }}"
        - "{{ make }}"
        - "{{ miniupnpc }}"
        - "{{ ncurses_base }}"
        - "{{ net_tools }}"
        - "{{ nmap }}"
        - "{{ openssl }}"
        - "{{ pipenv }}"
        - "{{ python3 }}"
        - "{{ python_is_python3 }}"
        - "{{ tcpdump }}"
        - "{{ tmux }}"
        - "{{ unar }}"
        - "{{ unzip }}"
        - "{{ vim }}"
        - "{{ wget }}"
        - "{{ whois }}"
        - "{{ wmctrl }}"
        - "{{ xsel }}"
        - "{{ xz_utils }}"
        - "{{ zlib1g_dev }}"
        - "{{ telnet }}"
        - "{{ netcat }}"
        - "{{ printer_driver }}"
      state: latest
