---
sqlite: sqlite-devel
crontab: cronie
libreadline: readline-devel
libpq: libpq
printer_driver: printer-driver-all
cfssl: golang-github-cloudflare-cfssl
proxychains: proxychains-ng
pyvenv: python3-virtualenv
imagemagick: ImageMagick
netcat: netcat
protobuf: "protobuf,protobuf-devel,protobuf-lite"
texlive: texlive-scheme-full
libncursesdev: ncurses-devel 
libssl_dev: openssl-devel
tkinter: tk-devel
