# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="spaceship"

# Ensure mozilla firefox works on wayland
export MOZ_ENABLE_WAYLAND=1

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Set vim keybindings
bindkey -v

# Reset for vi mode spaceship. See https://github.com/spaceship-prompt/spaceship-vi-mode
export RPS1="%{$reset_color%}"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=( git spaceship-vi-mode zsh-syntax-highlighting zsh-autosuggestions z )

autoload -Uz compinit
compinit

# Aliases
# add alias shortcut for proxychains
alias pc="proxychains"
# alias for easy tmux cleanup
alias tmux-cleanup='for x in $(tmux list-sessions | grep -E -i "^[[:digit:]]" | awk -F ":" "{print \$1}"); do tmux kill-session -t $x; done'
# setup toolbox helper
alias devbox='toolbox run -c devs tmux'
# run kubectl on host. For some reason normal hostspawn isn't working...
alias k='host-spawn kubectl'

# Indicate authentication for kubectl
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# setup pyenv, if installed 
# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# setup nvm, if installed
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set history by session
unsetopt inc_append_history
unsetopt share_history
setopt APPEND_HISTORY

# setup direnv, if isntalled
command -v direnv >/dev/null || eval "$(direnv hook zsh)" 

# Autocomplete kubectl
[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"

# Setup nix
[ -f "/etc/profile.d/nix.sh" ] && source "/etc/profile.d/nix.sh"
[ -f "$HOME/.nix-profile/etc/profile.d/nix.sh" ] && source "$HOME/.nix-profile/etc/profile.d/nix.sh"
[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ] && source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
[ -f "$HOME/.ghcup/env" ] && source "$HOME/.ghcup/env" # ghcup-env

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/crosley/temp/google-cloud-sdk/path.zsh.inc' ]; then . '/home/crosley/temp/google-cloud-sdk/path.zsh.inc'; fi
# The next line enables shell command completion for gcloud.
if [ -f '/home/crosley/temp/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/crosley/temp/google-cloud-sdk/completion.zsh.inc'; fi

# Use atuin
if [ -d $HOME/.atuin/bin ]; then
    eval "$(atuin init zsh)"
    . "$HOME/.atuin/bin/env"
fi

PATH="$PATH:/usr/sbin:$HOME/bin:/usr/local/sbin"

source $ZSH/oh-my-zsh.sh

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform
