{ config, pkgs, ... }:

{
  home.packages = with pkgs; [
    claude-code
  ];
  # config file
  home.file.claude_settings = {
    enable = true;
    target = ".claude/settings.json";
    text = ''
{
    "env": {
        "SHELL": "${pkgs.zsh}/bin/zsh",
        "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": "1",
        "DISABLE_TELEMETRY": "1",
        "DISABLE_ERROR_REPORTING": "1"
    },
    "permissions": {
        "allowBypassPermissions": false,
        "allow": [
            "Bash(* --version)",
            "Bash(* --help)",
            "Bash(grep *)",
            "Bash(cat *)",
            "Bash(ls *)",
            "Bash(head *)",
            "Bash(tail *)",
            "Bash(find *)",
            "Bash(git diff *)",
            "Bash(git log *)",
            "Bash(git status *)",
            "Bash(go test *)",
            "Bash(go doc *)",
            "Bash(go build *)",
            "Bash(golangci-lint *)",
            "Bash(terraform plan *)",
            "Bash(terraform show *)",
            "Bash(terraform validate *)",
            "Bash(terraform state show *)",
            "Bash(terraform state list *)",
            "Bash(gcloud run services describe *)",
            "Bash(gcloud run services list *)",
            "Bash(gcloud run jobs describe *)",
            "Bash(gcloud run jobs list *)",
            "Bash(gcloud logging read *)",
            "Bash(docker ps *)",
            "Bash(docker logs *)",
            "Bash(docker inspect *)",
            "Bash(docker images *)",
            "Bash(kubectl get *)",
            "Bash(kubectl describe *)",
            "Bash(kubectl logs *)",
            "Bash(aws * describe-* *)",
            "Bash(aws * list-* *)",
            "Bash(aws * get-* *)",
            "Read(${config.home.homeDirectory}/**)",
            "Read(/tmp/claude*/**)"
        ], 
        "ask": [
            "Write(${config.home.homeDirectory}/**)",
            "Write(/tmp/claude*/**)",
            "Edit(${config.home.homeDirectory}/**)",
            "Edit(/tmp/claude*/**)",
            "WebFetch",
            "WebSearch",
            "Bash(terraform apply *)",
            "Bash(terraform import *)",
            "Bash(terraform taint *)",
            "Bash(terraform state mv *)",
            "Bash(gcloud * create *)",
            "Bash(gcloud * update *)",
            "Bash(gcloud * deploy *)",
            "Bash(gcloud run deploy *)",
            "Bash(kubectl apply *)",
            "Bash(kubectl create *)",
            "Bash(kubectl delete *)",
            "Bash(kubectl edit *)",
            "Bash(kubectl patch *)",
            "Bash(kubectl scale *)",
            "Bash(kubectl rollout restart *)",
            "Bash(kubectl exec *)",
            "Bash(kubectl port-forward *)",
            "Bash(docker rm *)",
            "Bash(docker rmi *)",
            "Bash(docker kill *)",
            "Bash(docker stop *)",
            "Bash(docker exec *)",
            "Bash(aws * put-* *)",
            "Bash(aws * create-* *)",
            "Bash(aws * update-* *)",
            "Bash(aws * modify-* *)",
            "Bash(aws * stop-* *)",
            "Bash(npm install *)",
            "Bash(npm ci *)",
            "Bash(yarn install *)",
            "Bash(pnpm install *)",
            "Bash(npm publish *)",
            "Bash(pip install *)",
            "Bash(go get *)",
            "Bash(go install *)",
            "Bash(helm install *)",
            "Bash(helm upgrade *)",
            "Bash(ansible-playbook *)",
            "Bash(git add *)",
            "Bash(git commit *)",
            "Bash(git push *)",
            "Bash(git pull *)",
            "Bash(git merge *)",
            "Bash(git rebase *)",
            "Bash(git cherry-pick *)"
        ],
        "deny": [
            "Read(*.pem)",
            "Read(credentials*)",
            "Read(secrets/*)",
            "Read(**/.env)",
            "Read(**/.env.*)",
            "Read(**/*password*)",
            "Read(**/*secret*)",
            "Read(**/*token*)",
            "Read(${config.home.homeDirectory}/.ssh/**)",
            "Read(id_rsa*)",
            "Read(id_dsa*)",
            "Read(id_ecdsa*)",
            "Read(id_ed25519*)",
            "Read(*.ppk)",
            "Read(authorized_keys)",
            "Read(known_hosts)",
            "Read(*.keystore)",
            "Read(*.jks)",
            "Read(*.p12)",
            "Read(*.pfx)",
            "Read(*.ovpn)",
            "Read(${config.home.homeDirectory}/.aws/**)",
            "Read(${config.home.homeDirectory}/.config/gcloud/**)",
            "Read(${config.home.homeDirectory}/.azure/**)",
            "Read(${config.home.homeDirectory}/.kube/config)",
            "Read(${config.home.homeDirectory}/.docker/config.json)",
            "Read(${config.home.homeDirectory}/.gnupg/**)",
            "Read(${config.home.homeDirectory}/.password-store/**)",
            "Edit(*.pem)",
            "Edit(*.key)",
            "Edit(package-lock.json)",
            "Edit(**/.env)",
            "Edit(**/.env.*)",
            "Edit(**/*password*)",
            "Edit(**/*secret*)",
            "Edit(**/*token*)",
            "Edit(${config.home.homeDirectory}/.ssh/**)",
            "Edit(*.keystore)",
            "Edit(*.jks)",
            "Edit(*.p12)",
            "Edit(*.pfx)",
            "Edit(${config.home.homeDirectory}/.aws/**)",
            "Edit(${config.home.homeDirectory}/.config/gcloud/**)",
            "Edit(${config.home.homeDirectory}/.kube/config)",
            "Edit(${config.home.homeDirectory}/.gnupg/**)",
            "Edit(${config.home.homeDirectory}/.password-store/**)",
            "Write(*.pem)",
            "Write(*.key)",
            "Write(id_rsa*)",
            "Write(**/.env)",
            "Write(**/*password*)",
            "Write(**/*secret*)",
            "Write(**/*token*)",
            "Write(${config.home.homeDirectory}/.ssh/**)",
            "Write(*.keystore)",
            "Write(*.jks)",
            "Write(*.p12)",
            "Write(*.pfx)",
            "Write(${config.home.homeDirectory}/.aws/**)",
            "Write(${config.home.homeDirectory}/.config/gcloud/**)",
            "Write(${config.home.homeDirectory}/.kube/config)",
            "Write(${config.home.homeDirectory}/.gnupg/**)",
            "Write(${config.home.homeDirectory}/.password-store/**)",
            "Bash(* rm -rf *)",
            "Bash(* git push --force *)",
            "Bash(* git yolo *)",
            "Bash(* git reset --hard *)",
            "Bash(* sudo *)",
            "Bash(* su *)",
            "Bash(* ssh *)",
            "Bash(* chmod 777 *)",
            "Bash(* nc*)",
            "Bash(* netcat *)",
            "Bash(* socat *)",
            "Bash(* nmap *)",
            "Bash(* masscan *)",
            "Bash(* passwd *)",
            "Bash(* mkfs *)",
            "Bash(* fdisk *)",
            "Bash(* parted *)",
            "Bash(* dd *)",
            "Bash(* crontab *)",
            "Bash(* kill *)",
            "Bash(* killall *)",
            "Bash(* >/dev/sd *)",
            "Bash(* curl * | bash *)",
            "Bash(* wget * | bash *)",
            "Bash(* curl * | sh *)",
            "Bash(* wget * | sh *)",
            "Bash(* eval *)",
            "Bash(* exec *)",
            "Bash(* systemctl *)",
            "Bash(* useradd *)",
            "Bash(* usermod *)",
            "Bash(* userdel *)",
            "Bash(* mount *)",
            "Bash(* umount *)",
            "Bash(* iptables *)",
            "Bash(* ufw *)",
            "Bash(* chown -R *)",
            "Bash(* docker run --privileged *)",
            "Bash(* insmod *)",
            "Bash(* rmmod *)",
            "Bash(* modprobe *)",
            "Bash(* pkexec *)",
            "Bash(* doas *)",
            "Bash(* terraform destroy *)",
            "Bash(* terraform state rm *)",
            "Bash(* terraform force-unlock *)",
            "Bash(* terraform workspace delete *)",
            "Bash(* gcloud * delete *)",
            "Bash(* gcloud projects delete *)",
            "Bash(* gcloud sql instances delete *)",
            "Bash(* gcloud container clusters delete *)",
            "Bash(* kubectl delete namespace *)",
            "Bash(* kubectl delete pv *)",
            "Bash(* kubectl delete pvc *)",
            "Bash(* kubectl drain *)",
            "Bash(* docker system prune *)",
            "Bash(* docker volume prune *)",
            "Bash(* docker network prune *)",
            "Bash(* aws * delete-* *)",
            "Bash(* aws * terminate-* *)",
            "Bash(* aws rds delete-* *)",
            "Bash(* aws s3 rm * --recursive *)",
            "Bash(* aws s3api delete-* *)",
            "Bash(* helm uninstall *)",
            "Bash(* helm delete *)",
            "Bash(* kind delete cluster *)",
            "Bash(* k3d cluster delete *)",
            "Bash(* vagrant destroy *)",
            "Bash(* npm unpublish *)"
        ]
    },
    "hooks": {
        "PostToolUse": [
            {
                "matcher": "Write|Edit",
                "hooks": [
                    {
                    "type": "command",
                    "command": "gofmt -w \"$FILE_PATH\" 2>/dev/null || true",
                    "async": true
                    }
                ]
            }
        ],
        "UserPromptSubmit": [
            {
                "hooks": [
                    {
                    "type": "command",
                    "command": "git diff --stat 2>/dev/null || true",
                    "statusMessage": "Checking git status..."
                    }
                ]
            }
        ]
    },
    "respectGitignore": true,
    "includeCoAuthoredBy": false,
    "cleanupPeriodDays": 14
}
    '';
  };
  home.file.claude = {
    enable = true;
    target = ".claude/CLAUDE.md";
    text = ''
Read all links you are given; they have critical context
You can run read-only commands, but always ask before writing.
Always show you work and explain why you are doing this
Go packages should always have an interface, a struct implementing that interface, a mock of the interface, and comprehensive tests for every method
Function test should use table-driven pattern and compare the full output object to the expected output object; use cmp.Diff for structs
   '';
  };
}
